Repository PLOTTING-PLOWER/plotting-BE, pull requests merged in 2024-11, with the labels that each got.

#21 ✨ 플로깅 검색, 플로깅 모임 등록
  .github/workflows/prod-cicd.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/plotting/server/PlottingApplication.java
  src/main/java/com/plotting/server/global/application/S3Service.java
  src/main/java/com/plotting/server/global/config/FeignConfig.java
  src/main/java/com/plotting/server/global/config/QueryDslConfig.java
  src/main/java/com/plotting/server/global/config/S3Config.java
  src/main/java/com/plotting/server/global/controller/GlobalController.java
  src/main/java/com/plotting/server/global/dto/request/ImageUploadTestRequest.java
  src/main/java/com/plotting/server/global/exception/FileConvertFailException.java
  src/main/java/com/plotting/server/global/util/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/plotting/server/plogging/application/GeocodeService.java
  src/main/java/com/plotting/server/plogging/application/PloggingService.java
  src/main/java/com/plotting/server/plogging/application/PloggingServiceFacade.java
  src/main/java/com/plotting/server/plogging/domain/Plogging.java
  src/main/java/com/plotting/server/plogging/dto/request/PloggingRequest.java
  src/main/java/com/plotting/server/plogging/dto/response/GeocodeResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingListResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingResponse.java
  src/main/java/com/plotting/server/plogging/presentation/GeocodeClient.java
  src/main/java/com/plotting/server/plogging/presentation/PloggingController.java
  src/main/java/com/plotting/server/plogging/repository/PloggingRepository.java
  src/main/java/com/plotting/server/plogging/repository/PloggingRepositoryCustom.java
  src/main/java/com/plotting/server/plogging/repository/PloggingRepositoryCustomImpl.java
  src/main/java/com/plotting/server/plogging/repository/PloggingStarRepository.java
  src/main/java/com/plotting/server/plogging/repository/init/PloggingInitializer.java
  src/main/java/com/plotting/server/plogging/repository/init/PloggingStarInitializer.java
  src/main/resources/logback-spring.xml
  src/main/resources/logs/common/file-error-appender.xml
  src/main/resources/logs/common/file-info-appender.xml
  src/main/resources/logs/common/file-warn-appender.xml
  src/main/resources/logs/console-appender.xml
  src/main/resources/logs/error/file-error-appender.xml
  src/main/resources/logs/error/file-info-appender.xml
  src/main/resources/logs/error/file-warn-appender.xml
Labels: 📬 API, ✨ Feature, ⚙ Setting

#24 ✨ 댓글 관련 기능
  src/main/java/com/plotting/server/comment/application/CommentService.java
  src/main/java/com/plotting/server/comment/domain/Comment.java
  src/main/java/com/plotting/server/comment/dto/request/CommentRequest.java
  src/main/java/com/plotting/server/comment/dto/request/CommentUpdateRequest.java
  src/main/java/com/plotting/server/comment/dto/response/CommentListResponse.java
  src/main/java/com/plotting/server/comment/dto/response/CommentResponse.java
  src/main/java/com/plotting/server/comment/exception/CommentNotFoundException.java
  src/main/java/com/plotting/server/comment/exception/errorcode/CommentErrorCode.java
  src/main/java/com/plotting/server/comment/presentation/CommentController.java
  src/main/java/com/plotting/server/comment/repository/CommentRepository.java
  src/main/java/com/plotting/server/comment/repository/init/CommentInitializer.java
  src/main/java/com/plotting/server/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingDetailResponse.java
  src/main/java/com/plotting/server/user/repository/init/UserInitializer.java
  src/test/java/com/plotting/server/comment/application/CommentServiceTest.java
  src/test/java/com/plotting/server/comment/fixture/CommentFixture.java
Labels: 📬 API, ✨ Feature, 🔨 Refactor, ✅ Test

#27 ✨홈 조회 기능
  src/main/java/com/plotting/server/cardnews/application/CardnewsService.java
  src/main/java/com/plotting/server/cardnews/dto/response/CardResponse.java
  src/main/java/com/plotting/server/cardnews/dto/response/CardResponseList.java
  src/main/java/com/plotting/server/cardnews/dto/response/CardnewsResponse.java
  src/main/java/com/plotting/server/cardnews/dto/response/CardnewsResponseList.java
  src/main/java/com/plotting/server/cardnews/exception/CardNewsNotFoundException.java
  src/main/java/com/plotting/server/cardnews/exception/errorcode/CardnewsErrorCode.java
  src/main/java/com/plotting/server/cardnews/presentation/CardnewsController.java
  src/main/java/com/plotting/server/cardnews/repository/CardRepository.java
  src/main/java/com/plotting/server/cardnews/repository/CardnewsRepository.java
  src/main/java/com/plotting/server/cardnews/repository/init/CardInitializer.java
  src/main/java/com/plotting/server/cardnews/repository/init/CardnewsInitializer.java
  src/main/java/com/plotting/server/global/application/S3Service.java
  src/main/java/com/plotting/server/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/plotting/server/plogging/application/PloggingService.java
  src/main/java/com/plotting/server/plogging/dto/response/HomeResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/PlowerListResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/PlowerResponse.java
  src/main/java/com/plotting/server/plogging/repository/init/PloggingInitializer.java
  src/main/java/com/plotting/server/user/repository/UserRepository.java
  src/main/java/com/plotting/server/user/repository/UserStarRepository.java
  src/main/java/com/plotting/server/user/repository/init/UserInitializer.java
  src/main/java/com/plotting/server/user/repository/init/UserStarInitializer.java
Labels: 📬 API, ✨ Feature

#30 ✨ feat: 지도 api 구현
  src/main/java/com/plotting/server/plogging/application/PloggingMapService.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingMapResponse.java
  src/main/java/com/plotting/server/plogging/presentation/PloggingController.java
  src/main/java/com/plotting/server/plogging/repository/PloggingMapRepository.java
  src/main/java/com/plotting/server/plogging/repository/init/PloggingInitializer.java
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#35 ✨ feat 로그인
  build.gradle
  src/main/java/com/plotting/server/global/config/SecurityConfig.java
  src/main/java/com/plotting/server/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/plotting/server/global/util/JwtUtil.java
  src/main/java/com/plotting/server/user/application/AuthService.java
  src/main/java/com/plotting/server/user/application/CustomOAuth2UserService.java
  src/main/java/com/plotting/server/user/application/UserDetailsServiceImpl.java
  src/main/java/com/plotting/server/user/application/UserService.java
  src/main/java/com/plotting/server/user/dto/OAuthAttributes.java
  src/main/java/com/plotting/server/user/dto/request/LoginRequest.java
  src/main/java/com/plotting/server/user/dto/request/SignUpRequest.java
  src/main/java/com/plotting/server/user/dto/response/LoginResponse.java
  src/main/java/com/plotting/server/user/exception/UserAlreadyExistsException.java
  src/main/java/com/plotting/server/user/exception/errorcode/UserErrorCode.java
  src/main/java/com/plotting/server/user/presentation/AuthController.java
  src/main/java/com/plotting/server/user/presentation/CustomAuthenticationSuccessHandler.java
  src/main/java/com/plotting/server/user/repository/UserRepository.java
Labels: 📬 API, ✨ Feature

#41 ✨ 알림 관련 기능
  build.gradle
  src/main/java/com/plotting/server/alarm/application/AlarmService.java
  src/main/java/com/plotting/server/alarm/domain/Alarm.java
  src/main/java/com/plotting/server/alarm/repository/AlarmRepository.java
  src/main/java/com/plotting/server/comment/presentation/CommentController.java
  src/main/java/com/plotting/server/global/config/RedisConfig.java
  src/main/java/com/plotting/server/plogging/application/MyPloggingService.java
  src/main/java/com/plotting/server/plogging/application/PloggingService.java
  src/main/java/com/plotting/server/plogging/dto/request/PloggingUpdateRequest.java
  src/main/java/com/plotting/server/plogging/presentation/MyPloggingController.java
  src/main/java/com/plotting/server/plogging/presentation/PloggingController.java
  src/main/java/com/plotting/server/plogging/repository/init/PloggingUserInitializer.java
  src/main/java/com/plotting/server/plogging/util/PloggingConstants.java
  src/main/java/com/plotting/server/user/repository/init/UserInitializer.java
Labels: ✨ Feature

#43 ✨ 랭킹 api
  src/main/java/com/plotting/server/PlottingApplication.java
  src/main/java/com/plotting/server/global/config/SchedulingConfig.java
  src/main/java/com/plotting/server/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/plotting/server/plogging/application/MyPloggingService.java
  src/main/java/com/plotting/server/plogging/application/PloggingService.java
  src/main/java/com/plotting/server/plogging/domain/Plogging.java
  src/main/java/com/plotting/server/plogging/repository/PloggingRepository.java
  src/main/java/com/plotting/server/plogging/repository/init/PloggingInitializer.java
  src/main/java/com/plotting/server/ranking/application/RankingService.java
  src/main/java/com/plotting/server/ranking/application/RankingUpdateService.java
  src/main/java/com/plotting/server/ranking/domain/Ranking.java
  src/main/java/com/plotting/server/ranking/dto/response/CombineRankingResponse.java
  src/main/java/com/plotting/server/ranking/dto/response/RankingResponse.java
  src/main/java/com/plotting/server/ranking/dto/response/UpdateRankingListResponse.java
  src/main/java/com/plotting/server/ranking/dto/response/UpdateRankingResponse.java
  src/main/java/com/plotting/server/ranking/presentation/RankingController.java
  src/main/java/com/plotting/server/ranking/repository/RankingRepository.java
  src/main/java/com/plotting/server/user/application/UserService.java
  src/main/java/com/plotting/server/user/domain/User.java
  src/main/java/com/plotting/server/user/presentation/AuthController.java
  src/main/java/com/plotting/server/user/presentation/UserController.java
  src/main/java/com/plotting/server/user/presentation/UserStarController.java
Labels: 📬 API, ✨ Feature

#46 :bug: fix : 로그인 토큰 연결
  src/main/java/com/plotting/server/plogging/application/MyPloggingHomeService.java
  src/main/java/com/plotting/server/plogging/application/PloggingService.java
  src/main/java/com/plotting/server/plogging/dto/response/MyPloggingParticipatedResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/MyPloggingScheduledResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/MyPloggingSummaryResponse.java
  src/main/java/com/plotting/server/plogging/presentation/MyPloggingController.java
  src/main/java/com/plotting/server/plogging/presentation/PloggingController.java
  src/main/java/com/plotting/server/plogging/repository/MyPloggingRepository.java
  src/main/java/com/plotting/server/plogging/repository/PloggingUserRepository.java
  src/main/java/com/plotting/server/plogging/repository/init/PloggingInitializer.java
Labels: 🌱 Enhance, 🔨 Refactor

#47 ♻️ 홈 조회 수정
  src/main/java/com/plotting/server/plogging/presentation/PloggingController.java
Labels: 🐞 BugFix, 📬 API, ✏️ Chore

#50 ✨+♻️ 알림 및 랭킹 수정
  .gitignore
  build.gradle
  src/main/java/com/plotting/server/alarm/application/AlarmService.java
  src/main/java/com/plotting/server/alarm/application/FcmService.java
  src/main/java/com/plotting/server/alarm/dto/request/AlarmRequest.java
  src/main/java/com/plotting/server/alarm/dto/response/AlarmListResponse.java
  src/main/java/com/plotting/server/alarm/dto/response/AlarmResponse.java
  src/main/java/com/plotting/server/alarm/exception/FcmFailedException.java
  src/main/java/com/plotting/server/alarm/exception/errorcode/AlarmErrorCode.java
  src/main/java/com/plotting/server/alarm/presentation/AlarmController.java
  src/main/java/com/plotting/server/alarm/repository/AlarmRepository.java
  src/main/java/com/plotting/server/alarm/repository/init/AlarmInitializer.java
  src/main/java/com/plotting/server/global/config/FirebaseConfig.java
  src/main/java/com/plotting/server/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/plotting/server/plogging/application/PloggingStarService.java
  src/main/java/com/plotting/server/plogging/presentation/PloggingStarController.java
  src/main/java/com/plotting/server/ranking/application/RankingService.java
  src/main/java/com/plotting/server/user/application/UserService.java
  src/main/java/com/plotting/server/user/application/UserStarService.java
  src/main/java/com/plotting/server/user/domain/User.java
  src/main/java/com/plotting/server/user/dto/request/SignUpRequest.java
  src/main/java/com/plotting/server/user/dto/response/DetailProfileResponse.java
  src/main/java/com/plotting/server/user/presentation/UserController.java
  src/main/java/com/plotting/server/user/presentation/UserStarController.java
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#51 ♻️ refactor : 즐겨찾기 추가, 랭킹, 로그인 수정
  src/main/java/com/plotting/server/plogging/application/MyPloggingHomeService.java
  src/main/java/com/plotting/server/plogging/application/PloggingMapService.java
  src/main/java/com/plotting/server/plogging/dto/response/MyPloggingParticipatedResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/MyPloggingScheduledResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/MyPloggingSummaryResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingMapResponse.java
  src/main/java/com/plotting/server/plogging/presentation/MyPloggingController.java
  src/main/java/com/plotting/server/plogging/presentation/PloggingController.java
Labels: 🐞 BugFix, 🌱 Enhance, 🔨 Refactor
