Repository PLOTTING-PLOWER/plotting-BE, pull requests merged in 2024-10, with the labels that each got.

#2 [Entity] 즐겨찾기, 카드뉴스 관련 엔티티 생성
  plotting/src/main/java/com/plotting/server/cardnews/application/CardnewsService.java
  plotting/src/main/java/com/plotting/server/cardnews/domain/Card.java
  plotting/src/main/java/com/plotting/server/cardnews/domain/Cardnews.java
  plotting/src/main/java/com/plotting/server/cardnews/dto/request/CardnewsRequest.java
  plotting/src/main/java/com/plotting/server/cardnews/dto/response/CardnewsResponse.java
  plotting/src/main/java/com/plotting/server/cardnews/exception/CardNewsNotFoundException.java
  plotting/src/main/java/com/plotting/server/cardnews/presentation/CardnewsController.java
  plotting/src/main/java/com/plotting/server/cardnews/repository/CardnewsRepository.java
  plotting/src/main/java/com/plotting/server/plogging/application/PloggingService.java
  plotting/src/main/java/com/plotting/server/plogging/domain/Plogging.java
  plotting/src/main/java/com/plotting/server/plogging/domain/PloggingStar.java
  plotting/src/main/java/com/plotting/server/plogging/dto/request/PloggingRequest.java
  plotting/src/main/java/com/plotting/server/plogging/dto/response/PloggingResponse.java
  plotting/src/main/java/com/plotting/server/plogging/exception/PloggingNotFoundException.java
  plotting/src/main/java/com/plotting/server/plogging/presentation/PloggingController.java
  plotting/src/main/java/com/plotting/server/plogging/repository/PloggingRepository.java
  plotting/src/main/java/com/plotting/server/user/application/UserService.java
  plotting/src/main/java/com/plotting/server/user/domain/User.java
  plotting/src/main/java/com/plotting/server/user/domain/UserStar.java
  plotting/src/main/java/com/plotting/server/user/dto/request/UserRequest.java
  plotting/src/main/java/com/plotting/server/user/dto/response/UserResponse.java
  plotting/src/main/java/com/plotting/server/user/exception/UserNotFoundException.java
  plotting/src/main/java/com/plotting/server/user/presentation/UserController.java
  plotting/src/main/java/com/plotting/server/user/repository/UserRepository.java
Labels: ⚙ Setting

#8 [Entity] 랭킹 댓글 알람 플로깅 참가 유저 도메인 추가
  plotting/src/main/java/com/plotting/server/alarm/application/AlarmService.java
  plotting/src/main/java/com/plotting/server/alarm/domain/Alarm.java
  plotting/src/main/java/com/plotting/server/alarm/dto/request/AlarmRequest.java
  plotting/src/main/java/com/plotting/server/alarm/dto/response/AlarmResponse.java
  plotting/src/main/java/com/plotting/server/alarm/exception/AlarmNotFoundException.java
  plotting/src/main/java/com/plotting/server/alarm/presentation/AlarmController.java
  plotting/src/main/java/com/plotting/server/alarm/repository/AlarmRepository.java
  plotting/src/main/java/com/plotting/server/comment/application/CommentService.java
  plotting/src/main/java/com/plotting/server/comment/domain/Comment.java
  plotting/src/main/java/com/plotting/server/comment/dto/request/CommentRequest.java
  plotting/src/main/java/com/plotting/server/comment/dto/response/CommentResponse.java
  plotting/src/main/java/com/plotting/server/comment/exception/CommentNotFoundException.java
  plotting/src/main/java/com/plotting/server/comment/presentation/CommentController.java
  plotting/src/main/java/com/plotting/server/comment/repository/CommentRepository.java
  plotting/src/main/java/com/plotting/server/global/BaseTimeEntity.java
  plotting/src/main/java/com/plotting/server/ploggingUser/application/PloggingUserService.java
  plotting/src/main/java/com/plotting/server/ploggingUser/domain/PloggingUser.java
  plotting/src/main/java/com/plotting/server/ploggingUser/dto/request/PloggingUserRequest.java
  plotting/src/main/java/com/plotting/server/ploggingUser/dto/response/PloggingUserResponse.java
  plotting/src/main/java/com/plotting/server/ploggingUser/exception/PloggingUserNotFoundException.java
  plotting/src/main/java/com/plotting/server/ploggingUser/presentation/PloggingUserController.java
  plotting/src/main/java/com/plotting/server/ploggingUser/repository/PloggingUserRepository.java
  plotting/src/main/java/com/plotting/server/ranking/application/RankingService.java
  plotting/src/main/java/com/plotting/server/ranking/domain/Ranking.java
  plotting/src/main/java/com/plotting/server/ranking/dto/request/RankingRequest.java
  plotting/src/main/java/com/plotting/server/ranking/dto/response/RankingResponse.java
  plotting/src/main/java/com/plotting/server/ranking/exception/RankingNotFoundException.java
  plotting/src/main/java/com/plotting/server/ranking/presentation/RankingController.java
  plotting/src/main/java/com/plotting/server/ranking/repository/RankingRepository.java
Labels: ⚙ Setting

#13 ♻️ refactor : ranking 칼럼명 수정
  src/main/java/com/plotting/server/ranking/domain/Ranking.java
Labels: 💾 Database

#19 ✨ 플로깅 상세 관련 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/plotting/server/cardnews/domain/Card.java
  src/main/java/com/plotting/server/cardnews/domain/Cardnews.java
  src/main/java/com/plotting/server/comment/domain/Comment.java
  src/main/java/com/plotting/server/global/config/JpaAuditingConfig.java
  src/main/java/com/plotting/server/global/config/SwaggerConfig.java
  src/main/java/com/plotting/server/global/domain/BaseTimeEntity.java
  src/main/java/com/plotting/server/global/dto/ResponseTemplate.java
  src/main/java/com/plotting/server/global/exception/errorcode/ErrorCode.java
  src/main/java/com/plotting/server/global/exception/errorcode/GlobalErrorCode.java
  src/main/java/com/plotting/server/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/plotting/server/global/exception/response/ErrorResponse.java
  src/main/java/com/plotting/server/global/util/DummyDataInit.java
  src/main/java/com/plotting/server/global/util/ErrorResponseUtil.java
  src/main/java/com/plotting/server/plogging/application/PloggingService.java
  src/main/java/com/plotting/server/plogging/application/PloggingServiceFacade.java
  src/main/java/com/plotting/server/plogging/domain/Plogging.java
  src/main/java/com/plotting/server/plogging/domain/PloggingUser.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingDetailResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingUserListResponse.java
  src/main/java/com/plotting/server/plogging/dto/response/PloggingUserResponse.java
  src/main/java/com/plotting/server/plogging/exception/PloggingNotFoundException.java
  src/main/java/com/plotting/server/plogging/exception/errorcode/PloggingErrorCode.java
  src/main/java/com/plotting/server/plogging/presentation/PloggingController.java
  src/main/java/com/plotting/server/plogging/repository/PloggingRepository.java
  src/main/java/com/plotting/server/plogging/repository/PloggingUserRepository.java
  src/main/java/com/plotting/server/plogging/repository/init/PloggingInitializer.java
  src/main/java/com/plotting/server/plogging/repository/init/PloggingUserInitializer.java
  src/main/java/com/plotting/server/plogging/util/PloggingConstants.java
  src/main/java/com/plotting/server/ploggingUser/application/PloggingUserService.java
  src/main/java/com/plotting/server/ploggingUser/dto/request/PloggingUserRequest.java
  src/main/java/com/plotting/server/ploggingUser/dto/response/PloggingUserResponse.java
  src/main/java/com/plotting/server/ploggingUser/exception/PloggingUserNotFoundException.java
  src/main/java/com/plotting/server/ploggingUser/presentation/PloggingUserController.java
  src/main/java/com/plotting/server/ploggingUser/repository/PloggingUserRepository.java
  src/main/java/com/plotting/server/user/application/UserService.java
  src/main/java/com/plotting/server/user/domain/User.java
  src/main/java/com/plotting/server/user/exception/UserNotFoundException.java
  src/main/java/com/plotting/server/user/exception/errorcode/UserErrorCode.java
  src/main/java/com/plotting/server/user/repository/UserRepository.java
  src/main/java/com/plotting/server/user/repository/init/UserInitializer.java
  src/test/java/com/plotting/server/PlottingApplicationTests.java
  src/test/java/com/plotting/server/plogging/application/PloggingConcurrentTest.java
  src/test/java/com/plotting/server/plogging/application/PloggingServiceTest.java
  src/test/java/com/plotting/server/plogging/fixture/PloggingFixture.java
  src/test/java/com/plotting/server/plogging/fixture/PloggingUserFixture.java
  src/test/java/com/plotting/server/user/fixture/UserFixture.java
  src/test/resources/application.yml
Labels: 📬 API, ✨ Feature, ✅ Test
